# errors/error_types.py
class ErrorType:
    NONE = "NONE"
    SYNTAX = "SYNTAX"
    NAME = "NAME"
    TYPE = "TYPE"
    IMPORT = "IMPORT"
    INDEX = "INDEX"
    VALUE = "VALUE"
    RUNTIME = "RUNTIME"
    LOGICAL = "LOGICAL"
    ZERO_DIVISION = "ZERO_DIVISION"
    KEY = "KEY"
    ATTRIBUTE = "ATTRIBUTE"
    FILE = "FILE"
    MEMORY = "MEMORY"
    SYSTEM = "SYSTEM"
    NETWORK = "NETWORK"
    ENCODING = "ENCODING"
    ARITHMETIC = "ARITHMETIC"
    REGEX = "REGEX"
    PARSE = "PARSE"
    RECURSION = "RECURSION"
